#ifndef CPU_INSTRUCTIONS_MOS_6510_HH
#define CPU_INSTRUCTIONS_MOS_6510_HH

#include "and.hh"
#include "bcc.hh"
#include "bcs.hh"
#include "beq.hh"
#include "bne.hh"
#include "bpl.hh"
#include "clc.hh"
#include "cld.hh"
#include "cmp.hh"
#include "dex.hh"
#include "dey.hh"
#include "inc.hh"
#include "inx.hh"
#include "iny.hh"
#include "jmp.hh"
#include "jsr.hh"
#include "lda.hh"
#include "ldx.hh"
#include "ldy.hh"
#include "nop.hh"
#include "ora.hh"
#include "rol.hh"
#include "ror.hh"
#include "rts.hh"
#include "sei.hh"
#include "sta.hh"
#include "stx.hh"
#include "sty.hh"
#include "tax.hh"
#include "tay.hh"
#include "txa.hh"
#include "txs.hh"
#include "tya.hh"

#endif

